"""
Train the source-domain Attention U-Net for myoma segmentation on MRI.

Compatible with the output structure generated by `mri_pipeline.py`:
    <base_path>/
        train/images/*.npy  &  train/masks/*.npy
        val/images/*.npy    &  val/masks/*.npy
        test/images/*.npy   &  test/masks/*.npy

The preprocessing pipeline already performs patient-level splitting. This
script consumes those splits directly and does not split again, preserving
patient-level statistical isolation.

Usage:
    python scripts/training/train_source.py

Requirements:
    pip install python-dotenv torch numpy scikit-learn scipy scikit-image
"""

from __future__ import annotations

import csv
import datetime
import glob
import logging
import os
import re
import sys
import time
from pathlib import Path

import numpy as np
import torch
from torch.optim.lr_scheduler import ReduceLROnPlateau
from torch.utils.data import DataLoader, Dataset

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))

from config import CONFIG
from models.attention_unet import AttentionUNet, bce_dice_loss, compute_all_metrics


logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    datefmt="%H:%M:%S",
)
log = logging.getLogger(__name__)


def load_split_paths(
    base_path: str,
    split: str,
) -> tuple[list[str], list[str]]:
    """
    Load image and mask paths for one split.

    Expected structure:
        <base_path>/<split>/images/*.npy
        <base_path>/<split>/masks/*.npy

    Returns sorted `(img_paths, mask_paths)` lists with matching lengths.
    """
    img_dir = os.path.join(base_path, split, "images")
    mask_dir = os.path.join(base_path, split, "masks")

    imgs = sorted(glob.glob(os.path.join(img_dir, "*.npy")))
    masks = sorted(glob.glob(os.path.join(mask_dir, "*.npy")))

    if not imgs:
        raise FileNotFoundError(
            f"No .npy files were found in '{img_dir}'.\n"
            "Check DATA_PATH in `.env` and confirm that mri_pipeline.py has run."
        )
    if len(imgs) != len(masks):
        raise ValueError(
            f"Imbalance in split '{split}': "
            f"{len(imgs)} images vs {len(masks)} masks."
        )

    log.info(
        "Split %-5s -> %d image/mask pairs loaded.",
        split, len(imgs),
    )
    return imgs, masks


def get_patient_id(path: str) -> str:
    """
    Extract the patient ID from a processed `.npy` filename.

    Expected format: `{patient_id}_sag_{slice_index}.npy`.
    Example: `PAT_042_sag_37.npy` -> `PAT_042`.
    """
    stem = Path(path).stem
    m = re.match(r"^(.+)_sag_\d+$", stem)
    return m.group(1) if m else stem


def log_split_diagnostics(imgs: list[str], split: str) -> None:
    """
    Log per-patient slice distribution for one split.

    Warn when one patient contributes more than 10% of the split, because that
    can make validation metrics less representative.
    """
    groups = np.array([get_patient_id(p) for p in imgs])
    unique_patients = np.unique(groups)
    counts = [int((groups == pid).sum()) for pid in unique_patients]

    log.info(
        "  %-5s: %d slices | %d patients | "
        "slices/patient: min=%d max=%d mean=%.1f",
        split, len(imgs), len(unique_patients),
        min(counts), max(counts), np.mean(counts),
    )

    dominant = [
        pid for pid, c in zip(unique_patients, counts)
        if c / len(imgs) > 0.10
    ]
    if dominant:
        log.warning(
            "  Patients contributing >10%% of split '%s': %s. "
            "Consider lowering max_slices_per_patient in the pipeline.",
            split, dominant,
        )


class SagitalDataset(Dataset):
    """
    Dataset for preprocessed 2-D sagittal `.npy` slices.

    Each item is an `(image, mask)` pair shaped `(1, H, W)` as float32, ready for
    direct input to the Attention U-Net.
    """

    def __init__(self, img_paths: list[str], mask_paths: list[str]) -> None:
        assert len(img_paths) == len(mask_paths), (
            "img_paths and mask_paths must have the same length."
        )
        self.img_paths = img_paths
        self.mask_paths = mask_paths

    def __len__(self) -> int:
        return len(self.img_paths)

    def __getitem__(self, idx: int) -> tuple[torch.Tensor, torch.Tensor]:
        img = np.load(self.img_paths[idx]).astype(np.float32)
        mask = np.load(self.mask_paths[idx]).astype(np.float32)

        # Add channel dimension: (H, W) -> (1, H, W).
        return (
            torch.from_numpy(img).unsqueeze(0),
            torch.from_numpy(mask).unsqueeze(0),
        )


_CSV_HEADER = [
    "run_id", "epoch", "avg_loss",
    "dice", "hd95", "obj_precision",
    "hd95_inf_batches", "is_best", "lr", "timestamp",
]


def init_metrics_csv(run_id: str) -> str:
    """
    Create or append to the source-training metrics CSV.

    The header is written only when the file does not already exist.
    """
    os.makedirs(CONFIG["logs_path"], exist_ok=True)
    csv_path = os.path.join(CONFIG["logs_path"], "training_metrics.csv")

    if not os.path.exists(csv_path):
        with open(csv_path, "w", newline="", encoding="utf-8") as fh:
            csv.writer(fh).writerow(_CSV_HEADER)
        log.info("Metrics -> %s (new file)", csv_path)
    else:
        log.info("Metrics -> %s (append mode)", csv_path)

    return csv_path


def append_epoch_metrics(
    csv_path: str,
    run_id: str,
    epoch: int,
    avg_loss: float,
    metrics: dict,
    hd95_inf_batches: int,
    is_best: bool,
    current_lr: float,
) -> None:
    """Append metrics for one epoch to the CSV file."""
    hd95_val = metrics["HD95"]
    with open(csv_path, "a", newline="", encoding="utf-8") as fh:
        csv.writer(fh).writerow([
            run_id,
            epoch,
            f"{avg_loss:.6f}",
            f"{metrics['Dice']:.6f}",
            f"{hd95_val:.4f}" if np.isfinite(hd95_val) else "inf",
            f"{metrics['Object_Precision']:.6f}",
            hd95_inf_batches,
            int(is_best),
            f"{current_lr:.2e}",
            datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        ])


def validate(
    model: torch.nn.Module,
    val_loader: DataLoader,
    device: torch.device,
) -> tuple[dict, int]:
    """
    Evaluate the model on the validation split.

    Metrics are computed per batch and averaged at the end. Batches with
    infinite HD95 are counted but excluded from the HD95 mean to avoid
    distorting the reported value.
    """
    model.eval()
    batch_dices, batch_hd95s, batch_oprecs = [], [], []
    inf_count = 0

    with torch.no_grad():
        for images, masks in val_loader:
            images, masks = images.to(device), masks.to(device)
            metrics = compute_all_metrics(
                model(images), masks,
                threshold=CONFIG["threshold"],
                iou_threshold=CONFIG["iou_threshold"],
            )
            batch_dices.append(metrics["Dice"])
            batch_oprecs.append(metrics["Object_Precision"])

            if np.isfinite(metrics["HD95"]):
                batch_hd95s.append(metrics["HD95"])
            else:
                inf_count += 1

    if inf_count > 0:
        log.warning(
            "HD95=inf in %d validation batch(es). "
            "These batches are excluded from the HD95 mean.",
            inf_count,
        )

    return {
        "Dice": float(np.mean(batch_dices)) if batch_dices else 0.0,
        "HD95": float(np.mean(batch_hd95s)) if batch_hd95s else np.inf,
        "Object_Precision": float(np.mean(batch_oprecs)) if batch_oprecs else 0.0,
    }, inf_count


def run_epoch(
    model: torch.nn.Module,
    train_loader: DataLoader,
    optimizer: torch.optim.Optimizer,
    device: torch.device,
    epoch: int,
    log_every: int = 50,
) -> float:
    """Run one full training epoch and return the average batch loss."""
    model.train()
    total_loss = 0.0

    for step, (images, targets) in enumerate(train_loader):
        images, targets = images.to(device), targets.to(device)

        optimizer.zero_grad()
        loss = bce_dice_loss(model(images), targets)
        loss.backward()
        optimizer.step()

        total_loss += loss.item()

        if step % log_every == 0:
            log.info(
                "Ep %02d | Step %4d/%d | Loss: %.4f",
                epoch, step, len(train_loader), loss.item(),
            )

    return total_loss / len(train_loader)


def train() -> None:
    """
    Run source-domain training.

    Flow:
        1. Load splits prepared by `mri_pipeline.py`.
        2. Build DataLoaders without re-splitting.
        3. Initialize model, optimizer, scheduler, and metrics CSV.
        4. Run epoch loop with validation, checkpointing, and LR scheduling.
    """
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    run_id = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")

    log.info("=" * 60)
    log.info("  MiomaVision - source training")
    log.info("  Run ID:      %s", run_id)
    log.info("  Device:      %s", device)
    log.info("  Epochs:      %d", CONFIG["epochs"])
    log.info("  Initial LR:  %s", CONFIG["lr"])
    log.info("=" * 60)

    base_path = CONFIG["base_path"]

    tr_imgs, tr_masks = load_split_paths(base_path, "train")
    val_imgs, val_masks = load_split_paths(base_path, "val")

    log.info("- Split diagnostics -")
    log_split_diagnostics(tr_imgs, "train")
    log_split_diagnostics(val_imgs, "val")
    log.info("-" * 60)

    num_workers = CONFIG.get("num_workers", 0)
    pin_mem = device.type == "cuda"

    train_loader = DataLoader(
        SagitalDataset(tr_imgs, tr_masks),
        batch_size=CONFIG["batch_size"],
        shuffle=True,
        num_workers=num_workers,
        pin_memory=pin_mem,
    )
    val_loader = DataLoader(
        SagitalDataset(val_imgs, val_masks),
        batch_size=CONFIG["batch_size"],
        shuffle=False,
        num_workers=num_workers,
        pin_memory=pin_mem,
    )

    model = AttentionUNet(CONFIG["in_channels"], CONFIG["num_classes"]).to(device)
    optimizer = torch.optim.Adam(model.parameters(), lr=CONFIG["lr"])

    # Reduce LR when validation Dice plateaus, avoiding manual LR adjustment.
    scheduler = ReduceLROnPlateau(
        optimizer,
        mode="max",
        factor=CONFIG.get("lr_factor", 0.5),
        patience=CONFIG.get("lr_patience", 5),
        min_lr=CONFIG.get("lr_min", 1e-6),
    )

    csv_path = init_metrics_csv(run_id)

    best_dice = 0.0
    patience_counter = 0
    early_stop_patience = CONFIG.get("early_stop_patience", 0)

    for epoch in range(1, CONFIG["epochs"] + 1):
        t0 = time.time()

        avg_loss = run_epoch(model, train_loader, optimizer, device, epoch)
        val_metrics, inf_batches = validate(model, val_loader, device)

        dice_val = val_metrics["Dice"]
        hd95_val = val_metrics["HD95"]
        oprec_val = val_metrics["Object_Precision"]
        hd95_str = f"{hd95_val:.2f}px" if np.isfinite(hd95_val) else "inf"
        is_best = dice_val > best_dice
        elapsed = time.time() - t0

        current_lr = optimizer.param_groups[0]["lr"]
        prev_lr = current_lr
        scheduler.step(dice_val)
        new_lr = optimizer.param_groups[0]["lr"]

        log.info(
            "Epoch %02d/%02d | Loss: %.4f | Dice: %.4f | "
            "HD95: %s | ObjPrec: %.4f | LR: %.2e | %.1fs%s",
            epoch, CONFIG["epochs"],
            avg_loss, dice_val, hd95_str, oprec_val,
            current_lr, elapsed,
            " * BEST" if is_best else "",
        )

        if new_lr < prev_lr:
            log.info("  LR reduced: %.2e -> %.2e", prev_lr, new_lr)

        append_epoch_metrics(
            csv_path, run_id, epoch,
            avg_loss, val_metrics, inf_batches, is_best, current_lr,
        )

        if is_best:
            best_dice = dice_val
            patience_counter = 0
            torch.save(model.state_dict(), CONFIG["model_path"])
            log.info("  Checkpoint saved -> %s", CONFIG["model_path"])
        else:
            patience_counter += 1

        if early_stop_patience > 0 and patience_counter >= early_stop_patience:
            log.info(
                "Early stopping: Dice did not improve for %d consecutive epochs.",
                early_stop_patience,
            )
            break

    log.info("=" * 60)
    log.info("  Training finished")
    log.info("  Best Dice: %.4f", best_dice)
    log.info("  Metrics:   %s", csv_path)
    log.info("=" * 60)


if __name__ == "__main__":
    train()
